[providers]
  [providers.docker]
    exposedByDefault = false
    network = "gateway"

  [providers.file]
    directory = '/etc/traefik/dynamic'
    watch = true

[api]
  insecure = true
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"
        permanent = true

  [entryPoints.websecure]
    address = ":443"